FROM python:3.11.0-alpine3.16
LABEL maintainer="farhanAhmed"
ENV PYTHONUNBUFFERED 1
COPY ./requirements.txt /tmp/requirements.txt
COPY ./app /app
WORKDIR /app
EXPOSE  8000

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip  && \
    /py/bin/pip install /tmp/requirements.txt && \
    rm -rf /tmp && \
    adduser \
       --diasabled-password \
       --no-create-home \
       django-user

ENV path = "py/bin:$PATH"
user = django-user